(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.001) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
"GET /dashboard/ HTTP/1.1" 200 572
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
"GET /dashboard/ HTTP/1.1" 200 710
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
"GET /dashboard/ HTTP/1.1" 200 719
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" LIMIT 1; args=()
"GET /dashboard/ HTTP/1.1" 200 726
(0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
(0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
Not Found: /
"GET / HTTP/1.1" 404 2275
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:41:50.342570'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:41:50.342570')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f50369cf140>>, 'user': <SimpleLazyObject: <User: raj>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5036a44f50>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f503c02bdd0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f50369cf140>>, 'user': <SimpleLazyObject: <User: raj>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5036a44f50>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f503c02bdd0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
(0.000) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = 2 ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=(2,)
"GET /admin/ HTTP/1.1" 200 4139
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:17.540891'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:17.540891')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
(0.000) SELECT COUNT(*) AS "__count" FROM "core_basicdetails"; args=()
(0.000) SELECT COUNT(*) AS "__count" FROM "core_basicdetails"; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" ORDER BY "core_basicdetails"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5040b546e0>>}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
"GET /admin/core/basicdetails/ HTTP/1.1" 200 4234
(0.000) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:17.798529'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:17.798529')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
"GET /admin/jsi18n/ HTTP/1.1" 200 3217
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:19.476387'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:19.476387')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
(0.000) BEGIN; args=None
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" WHERE "core_basicdetails"."id" = 1; args=(1,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'basicdetails' AND "django_content_type"."app_label" = 'core'); args=('basicdetails', 'core')
"GET /admin/core/basicdetails/1/change/ HTTP/1.1" 200 5203
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:19.570052'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:19.570052')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
"GET /admin/jsi18n/ HTTP/1.1" 200 3217
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:29.688876'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:29.688876')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
(0.000) BEGIN; args=None
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" WHERE "core_basicdetails"."id" = 1; args=(1,)
(0.000) UPDATE "core_basicdetails" SET "phone_number" = 8750862568, "wake_up_time" = 7, "sleep_time" = 23 WHERE "core_basicdetails"."id" = 1; args=(8750862568, 7, 23, 1)
(0.000) INSERT INTO "django_admin_log" ("action_time", "user_id", "content_type_id", "object_id", "object_repr", "action_flag", "change_message") VALUES ('2018-07-19 18:43:29.696665', 2, 1, '1', '8750862568', 2, '[{"changed": {"fields": ["phone_number"]}}]'); args=[u'2018-07-19 18:43:29.696665', 2, 1, u'1', u'8750862568', 2, '[{"changed": {"fields": ["phone_number"]}}]']
"POST /admin/core/basicdetails/1/change/ HTTP/1.1" 302 0
(0.000) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:29.811695'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:29.811695')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
(0.000) SELECT COUNT(*) AS "__count" FROM "core_basicdetails"; args=()
(0.000) SELECT COUNT(*) AS "__count" FROM "core_basicdetails"; args=()
(0.000) SELECT "core_basicdetails"."id", "core_basicdetails"."phone_number", "core_basicdetails"."wake_up_time", "core_basicdetails"."sleep_time" FROM "core_basicdetails" ORDER BY "core_basicdetails"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5040b54500>>}]"
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
"GET /admin/core/basicdetails/ HTTP/1.1" 200 4431
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:29.879638'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:29.879638')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
"GET /admin/jsi18n/ HTTP/1.1" 200 3217
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:31.744852'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:31.744852')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5040b545f0>>, 'user': <SimpleLazyObject: <User: raj>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f50369ca850>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f503694f490>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5040b545f0>>, 'user': <SimpleLazyObject: <User: raj>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f50369ca850>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f503694f490>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
(0.000) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = 2 ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=(2,)
"GET /admin/ HTTP/1.1" 200 4475
(0.002) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:32.902180'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:32.902180')
(0.001) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
(0.000) SELECT COUNT(*) AS "__count" FROM "django_cron_cronjoblog"; args=()
(0.000) SELECT COUNT(*) AS "__count" FROM "django_cron_cronjoblog"; args=()
(0.000) SELECT "django_cron_cronjoblog"."id", "django_cron_cronjoblog"."code", "django_cron_cronjoblog"."start_time", "django_cron_cronjoblog"."end_time", "django_cron_cronjoblog"."is_success", "django_cron_cronjoblog"."message", "django_cron_cronjoblog"."ran_at_time" FROM "django_cron_cronjoblog" ORDER BY "django_cron_cronjoblog"."start_time" DESC, "django_cron_cronjoblog"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5040b540c8>>}]"
(0.000) SELECT DISTINCT "django_cron_cronjoblog"."code" FROM "django_cron_cronjoblog" ORDER BY "django_cron_cronjoblog"."code" ASC; args=()
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
"GET /admin/django_cron/cronjoblog/ HTTP/1.1" 200 7532
(0.000) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:33.011958'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:33.011958')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
"GET /admin/jsi18n/ HTTP/1.1" 200 3217
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:35.202378'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:35.202378')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
(0.000) BEGIN; args=None
(0.000) SELECT "django_cron_cronjoblog"."id", "django_cron_cronjoblog"."code", "django_cron_cronjoblog"."start_time", "django_cron_cronjoblog"."end_time", "django_cron_cronjoblog"."is_success", "django_cron_cronjoblog"."message", "django_cron_cronjoblog"."ran_at_time" FROM "django_cron_cronjoblog" WHERE "django_cron_cronjoblog"."id" = 1; args=(1,)
(0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'cronjoblog' AND "django_content_type"."app_label" = 'django_cron'); args=('cronjoblog', 'django_cron')
"GET /admin/django_cron/cronjoblog/1/change/ HTTP/1.1" 200 6582
"GET /static/admin/js/calendar.js HTTP/1.1" 200 7790
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20529
(0.000) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:35.325456'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:35.325456')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
"GET /admin/jsi18n/ HTTP/1.1" 200 3217
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:38.824023'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:38.824023')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
(0.000) SELECT COUNT(*) AS "__count" FROM "django_cron_cronjoblog"; args=()
(0.000) SELECT COUNT(*) AS "__count" FROM "django_cron_cronjoblog"; args=()
(0.000) SELECT "django_cron_cronjoblog"."id", "django_cron_cronjoblog"."code", "django_cron_cronjoblog"."start_time", "django_cron_cronjoblog"."end_time", "django_cron_cronjoblog"."is_success", "django_cron_cronjoblog"."message", "django_cron_cronjoblog"."ran_at_time" FROM "django_cron_cronjoblog" ORDER BY "django_cron_cronjoblog"."start_time" DESC, "django_cron_cronjoblog"."id" DESC; args=()
Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5040b541b8>>}]"
(0.000) SELECT DISTINCT "django_cron_cronjoblog"."code" FROM "django_cron_cronjoblog" ORDER BY "django_cron_cronjoblog"."code" ASC; args=()
Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
Exception while resolving variable 'non_field_errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [non_field_errors] in u'None'
"GET /admin/django_cron/cronjoblog/ HTTP/1.1" 200 7532
(0.001) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'ffuxz1wjww57ia12z86ghcg4mer3wjlh' AND "django_session"."expire_date" > '2018-07-19 18:43:41.978662'); args=('ffuxz1wjww57ia12z86ghcg4mer3wjlh', u'2018-07-19 18:43:41.978662')
(0.000) SELECT "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined" FROM "auth_user" WHERE "auth_user"."id" = 2; args=(2,)
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5040b54488>>, 'user': <SimpleLazyObject: <User: raj>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5036a34d50>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f50369c26d0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "/home/raj/Desktop/blahblahblah/SocialCops_assignment/amnesia_cron/venv/lib/python2.7/site-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x7f5040b54488>>, 'user': <SimpleLazyObject: <User: raj>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x7f5036a34d50>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x7f50369c26d0>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django administration', 'available_apps': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], 'site_title': u'Django site admin', 'title': u'Site administration', 'has_permission': True, 'app_list': [{'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'Groups', 'add_url': u'/admin/auth/group/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/auth/user/add/'}], 'has_module_perms': True, 'name': u'Authentication and Authorization', 'app_label': 'auth'}, {'app_url': u'/admin/core/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/core/basicdetails/', 'object_name': 'basicDetails', 'name': u'Basic detailss', 'add_url': u'/admin/core/basicdetails/add/'}], 'has_module_perms': True, 'name': 'Core', 'app_label': 'core'}, {'app_url': u'/admin/django_cron/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/django_cron/cronjoblog/', 'object_name': 'CronJobLog', 'name': u'Cron job logs', 'add_url': u'/admin/django_cron/cronjoblog/add/'}], 'has_module_perms': True, 'name': 'Django_Cron', 'app_label': 'django_cron'}], u'LANGUAGE_CODE': 'en-us', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
(0.000) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auth_user"."id", "auth_user"."password", "auth_user"."last_login", "auth_user"."is_superuser", "auth_user"."username", "auth_user"."first_name", "auth_user"."last_name", "auth_user"."email", "auth_user"."is_staff", "auth_user"."is_active", "auth_user"."date_joined", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auth_user" ON ("django_admin_log"."user_id" = "auth_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = 2 ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=(2,)
"GET /admin/ HTTP/1.1" 200 4475
